const productsData = [
    {
        id: "acb-air-circuit-breaker",
        productName: "Air Circuit Breaker (ACB)",
        manufacturerName: "Schneider / ABB / L&T",
        category: "Electrical Switching & Protection",
        subCategory: "Air Circuit Breakers",
        shortDescription: "High-current circuit protection for industrial plants.",
        fullDescription: "Robust Air Circuit Breakers designed for the protection of electrical circuits in industrial and building low-voltage distribution systems. Features high breaking capacity and selective protection.",
        image: "/devai/images/products/acb_air_circuit_breaker.png",
        datasheet: "#"
    },
    {
        id: "mccb-molded-case-circuit-breaker",
        productName: "Molded Case Circuit Breaker (MCCB)",
        manufacturerName: "Siemens / Legrand",
        category: "Electrical Switching & Protection",
        subCategory: "Moulded Case Circuit Breakers",
        shortDescription: "Reliable protection for distribution circuits.",
        fullDescription: "Molded Case Circuit Breakers provide protection against overloads and short circuits in electrical distribution systems. Available in various frame sizes and breaking capacities.",
        image: "/devai/images/products/mccb_molded_case_circuit_breaker.png",
        datasheet: "#"
    },
    {
        id: "mcb-miniature-circuit-breaker",
        productName: "Miniature Circuit Breaker (MCB)",
        manufacturerName: "Polycab / Havells",
        category: "Electrical Switching & Protection",
        subCategory: "Modular Circuit Breakers",
        shortDescription: "Compact protection for final distribution.",
        fullDescription: "Standard MCBs for protection of cables and equipment against overload and short circuits. Ideal for domestic and commercial installations.",
        image: "/devai/images/products/mcb_miniature_circuit_breaker.png",
        datasheet: "#"
    },
    {
        id: "electrical-contactor",
        productName: "Electrical Contactor",
        manufacturerName: "Schneider Electric",
        category: "Electrical Switching & Protection",
        subCategory: "Power Contactors",
        shortDescription: "Heavy-duty switching for motors and loads.",
        fullDescription: "High-performance contactors for controlling electric motors, lighting, heating, and capacitor banks. proven reliability in harsh industrial environments.",
        image: "/devai/images/products/electrical_contactor.png",
        datasheet: "#"
    },
    {
        id: "thermal-overload-relay",
        productName: "Thermal Overload Relay",
        manufacturerName: "L&T Switchgear",
        category: "Electrical Switching & Protection",
        subCategory: "Thermal Overload Relays",
        shortDescription: "Motor protection against overload and phase failure.",
        fullDescription: "Reliable thermal overload relays for direct mounting on contactors. Provides accurate protection for motors against thermal overload and phase loss.",
        image: "/devai/images/products/thermal_overload_relay.png",
        datasheet: "#"
    },
    {
        id: "mpcb-motor-protection",
        productName: "MPCB",
        manufacturerName: "Siemens",
        category: "Electrical Switching & Protection",
        subCategory: "Motor Protection Circuit Breakers",
        shortDescription: "Motor Protection Circuit Breaker.",
        fullDescription: "All-in-one motor protection solution combining short-circuit protection and overload protection in a single compact device.",
        image: "/devai/images/products/mpcb_motor_protection_circuit_breaker.png",
        datasheet: "#"
    },
    {
        id: "plc-automation",
        productName: "PLC Controller",
        manufacturerName: "Allen-Bradley / Mitsubishi",
        category: "Automation & Control Components",
        subCategory: "Programmable Logic Controllers",
        shortDescription: "Programmable Logic Controller for industrial automation.",
        fullDescription: "Advanced PLCs for complex machine control and process automation. Features modular design, high processing speed, and multiple communication protocols.",
        image: "/devai/images/products/plc_automation_controller.png",
        datasheet: "#"
    },
    {
        id: "hmi-touch-panel",
        productName: "HMI Touch Panel",
        manufacturerName: "Delta / Omron",
        category: "Automation & Control Components",
        subCategory: "Programmable Logic Controllers",
        shortDescription: "Human Machine Interface for system monitoring.",
        fullDescription: "High-resolution HMI touch screens for intuitive machine operation and monitoring. Supports data logging, remote access, and various industrial protocols.",
        image: "/devai/images/products/hmi_touch_panel_industrial.png",
        datasheet: "#"
    },
    {
        id: "vfd-drive",
        productName: "VFD Drive",
        manufacturerName: "Danfoss / Yaskawa",
        category: "Automation & Control Components",
        subCategory: "Variable Frequency Drive Systems",
        shortDescription: "Variable Frequency Drive for motor speed control.",
        fullDescription: "Energy-efficient AC drives for precise control of motor speed and torque. Ideal for pumps, fans, conveyors, and general automation applications.",
        image: "/devai/images/products/vfd_drive_industrial.png",
        datasheet: "#"
    },
    {
        id: "smps-power",
        productName: "Industrial SMPS",
        manufacturerName: "Mean Well",
        category: "Power Supply & Energy Management",
        subCategory: "Switch Mode Power Supplies",
        shortDescription: "Switched Mode Power Supply 24V DC.",
        fullDescription: "Reliable DIN-rail mounted power supplies for industrial control cabinets. Features high efficiency, wide input voltage range, and short-circuit protection.",
        image: "/devai/images/products/smps_power_supply_industrial.png",
        datasheet: "#"
    },
    {
        id: "inductive-sensor",
        productName: "Inductive Proximity Sensor",
        manufacturerName: "Sick / P&F",
        category: "Sensors",
        shortDescription: "Non-contact detection of metal objects.",
        fullDescription: "Rugged inductive sensors for position detection in automation. IP67 rated for harsh environments, available in various sensing ranges and outputs.",
        image: "/devai/images/products/inductive_proximity_sensor.png",
        datasheet: "#"
    },
    {
        id: "photoelectric-sensor",
        productName: "Photoelectric Sensor",
        manufacturerName: "Omron / Banner",
        category: "Sensors",
        shortDescription: "Optical detection for automation.",
        fullDescription: "Versatile photoelectric sensors for detecting objects regardless of material. Modes include through-beam, retro-reflective, and diffuse.",
        image: "/devai/images/products/photoelectric_sensor_industrial.png",
        datasheet: "#"
    },
    {
        id: "industrial-motor",
        productName: "Industrial Electric Motor",
        manufacturerName: "Bharat Bijlee / Crompton",
        category: "Motors",
        shortDescription: "Three-phase induction motor.",
        fullDescription: "High-efficiency IE2/IE3 induction motors for continuous industrial duty. Suitable for pumps, compressors, fans, and conveyor systems.",
        image: "/devai/images/products/industrial_electric_motor.png",
        datasheet: "#"
    },
    {
        id: "industrial-gearbox",
        productName: "Industrial Gearbox",
        manufacturerName: "Bonfiglioli",
        category: "Motors",
        shortDescription: "Heavy-duty transmission gearbox.",
        fullDescription: "Robust worm and helical gearboxes for torque multiplication and speed reduction. Designed for durability and smooth power transmission.",
        image: "/devai/images/products/industrial_gearbox.png",
        datasheet: "#"
    },
    {
        id: "armoured-cable",
        productName: "Armoured Power Cable",
        manufacturerName: "Polycab / KEI",
        category: "Cables",
        shortDescription: "XLPE insulated armoured cable.",
        fullDescription: "Heavy-duty armoured aluminum/copper cables for underground power distribution. Resistant to mechanical stress and environmental factors.",
        image: "/devai/images/products/armoured_electrical_cable.png",
        datasheet: "#"
    },
    {
        id: "cable-gland",
        productName: "Brass Cable Gland",
        manufacturerName: "Comet / Jainson",
        category: "Accessories",
        shortDescription: "Double compression brass gland.",
        fullDescription: "Weatherproof double compression cable glands for secure cable entry into panels and enclosures. IP66 rated for outdoor use.",
        image: "/devai/images/products/brass_cable_gland.png",
        datasheet: "#"
    },
    {
        id: "lt-control-panel",
        productName: "LT Control Panel",
        manufacturerName: "Custom / CPRI Approved",
        category: "Panels",
        shortDescription: "Low Tension Power Distribution Panel.",
        fullDescription: "Custom-built electrical command and control panels. Powder-coated rugged enclosures with high-quality busbars and switchgear layout.",
        image: "/devai/images/products/lt_control_panel.png",
        datasheet: "#"
    },
    {
        id: "led-flood-light",
        productName: "LED Flood Light",
        manufacturerName: "Philips / Bajaj",
        category: "Lighting",
        shortDescription: "High-intensity outdoor industrial lighting.",
        fullDescription: "Energy-saving LED floodlights for industrial yards, factories, and security lighting. IP65 waterproof housing with high lumen output.",
        image: "/devai/images/products/led_flood_light.png",
        datasheet: "#"
    },
    {
        id: "digital-multimeter",
        productName: "Digital Multimeter",
        manufacturerName: "Fluke 179",
        category: "Tools",
        shortDescription: "True-RMS Industrial Multimeter.",
        fullDescription: "Professional-grade digital multimeter for measuring voltage, current, resistance, and continuity. Essential for troubleshooting electrical systems.",
        image: "/devai/images/products/digital_multimeter_industrial.png",
        datasheet: "#"
    },
    {
        id: "power-tools",
        productName: "Industrial Power Tools",
        manufacturerName: "Bosch / Makita",
        category: "Tools",
        shortDescription: "Heavy-duty drill and grinder.",
        fullDescription: "Professional cordless and corded power tools for construction and maintenance. Ergonomic design with high durability.",
        image: "/devai/images/products/industrial_power_tools.png",
        datasheet: "#"
    },
    {
        id: "safety-switch",
        productName: "Safety Interlock Switch",
        manufacturerName: "Schmersal",
        category: "Safety",
        shortDescription: "Door safety switch for machine guarding.",
        fullDescription: "Safety interlock switches with solenoid locking. Prevents machine operation when guard doors are open, ensuring operator safety.",
        image: "/devai/images/products/door_safety_interlock_switch.png",
        datasheet: "#"
    },
    {
        id: "thermal-camera",
        productName: "Thermal Imaging Camera",
        manufacturerName: "FLIR",
        category: "Testing",
        shortDescription: "Infrared camera for hotspot detection.",
        fullDescription: "Handheld thermal imager for electrical inspections. Quickly identify overheating components, loose connections, and load imbalances.",
        image: "/devai/images/products/thermal_imaging_camera_industrial.png",
        datasheet: "#"
    },
    {
        id: "abs-enclosure",
        productName: "ABS Enclosure",
        manufacturerName: "Sibass / Hensel",
        category: "Enclosures",
        shortDescription: "Weatherproof IP65 Junction Box.",
        fullDescription: "Impact-resistant ABS/Polycarbonate enclosures for electrical junctions. UV stabilized and dustproof, suitable for outdoor installation.",
        image: "/devai/images/products/abs_electrical_enclosure.png",
        datasheet: "#"
    },
    {
        id: "industrial-bearing",
        productName: "Industrial Bearing",
        manufacturerName: "SKF / FAG",
        category: "Mechanical",
        shortDescription: "Ball and Roller Bearings.",
        fullDescription: "High-precision ball bearings for rotating machinery. Reduced friction and high load-carrying capacity for long service life.",
        image: "/devai/images/products/industrial_bearing.png",
        datasheet: "#"
    },
    {
        id: "clamp-meter",
        productName: "Clamp Meter",
        manufacturerName: "Fluke",
        category: "Testing",
        shortDescription: "AC/DC current measurement tool.",
        fullDescription: "Digital clamp meter for measuring AC/DC current, voltage, and resistance without breaking the circuit. Essential for electrical troubleshooting.",
        image: "/devai/images/products/clamp_meter_electrical.png",
        datasheet: "#"
    },
    {
        id: "cnc-machine-light",
        productName: "CNC Machine Light",
        manufacturerName: "Custom",
        category: "Lighting",
        shortDescription: "LED lighting for CNC machines.",
        fullDescription: "High-brightness LED lights designed for illuminating CNC machine work areas, providing clear visibility for precision operations.",
        image: "/devai/images/products/cnc_machine_light.png",
        datasheet: "#"
    },
    {
        id: "control-relay",
        productName: "Control Relay",
        manufacturerName: "Omron",
        category: "Controlgear",
        shortDescription: "Electromechanical relay for control circuits.",
        fullDescription: "Reliable control relays for switching low-power signals in industrial control systems. Features multiple contacts and long service life.",
        image: "/devai/images/products/control_relay_industrial.png",
        datasheet: "#"
    },
    {
        id: "din-rail-power-supply",
        productName: "DIN Rail Power Supply",
        manufacturerName: "Siemens",
        category: "Power Supply",
        shortDescription: "24V DC power supply for DIN rail mounting.",
        fullDescription: "Compact DIN-rail mounted power supplies for industrial applications, providing stable 24V DC output with overload protection.",
        image: "/devai/images/products/din_rail_power_supply.png",
        datasheet: "#"
    },
    {
        id: "industrial-contactor-alt",
        productName: "Industrial Contactor",
        manufacturerName: "ABB",
        category: "Controlgear",
        shortDescription: "Heavy-duty contactor for industrial use.",
        fullDescription: "Robust contactors for controlling high-power electrical loads in industrial environments. Features arc suppression and high durability.",
        image: "/devai/images/products/industrial_contactor.png",
        datasheet: "#"
    },
    {
        id: "industrial-ethernet-switch",
        productName: "Industrial Ethernet Switch",
        manufacturerName: "Moxa",
        category: "Automation",
        shortDescription: "Managed Ethernet switch for industrial networks.",
        fullDescription: "Rugged Ethernet switches for industrial automation networks, supporting Gigabit speeds and redundant power inputs.",
        image: "/devai/images/products/industrial_ethernet_switch.png",
        datasheet: "#"
    },
    {
        id: "industrial-power-connector",
        productName: "Industrial Power Connector",
        manufacturerName: "Harting",
        category: "Accessories",
        shortDescription: "Heavy-duty power connector.",
        fullDescription: "IP67 rated power connectors for reliable electrical connections in industrial applications.",
        image: "/devai/images/products/industrial_power_connector.png",
        datasheet: "#"
    },
    {
        id: "industrial-ups",
        productName: "Industrial UPS System",
        manufacturerName: "APC",
        category: "Power Supply",
        shortDescription: "Uninterruptible Power Supply for industrial equipment.",
        fullDescription: "Online UPS systems providing backup power and surge protection for critical industrial loads.",
        image: "/devai/images/products/industrial_ups_system.png",
        datasheet: "#"
    },
    {
        id: "led-high-bay-light",
        productName: "LED High Bay Light",
        manufacturerName: "Osram",
        category: "Lighting",
        shortDescription: "High-intensity LED for warehouses.",
        fullDescription: "Energy-efficient LED high bay lights for illuminating large industrial spaces like warehouses and factories.",
        image: "/devai/images/products/led_high_bay_light.png",
        datasheet: "#"
    },
    {
        id: "led-street-light",
        productName: "LED Street Light",
        manufacturerName: "Bajaj",
        category: "Lighting",
        shortDescription: "Outdoor LED street lighting.",
        fullDescription: "Solar-powered or grid-connected LED street lights for urban and industrial road lighting.",
        image: "/devai/images/products/led_street_light.png",
        datasheet: "#"
    },
    {
        id: "limit-switch",
        productName: "Limit Switch",
        manufacturerName: "Honeywell",
        category: "Sensors",
        shortDescription: "Position sensing switch.",
        fullDescription: "Mechanical limit switches for detecting the presence or position of objects in automation systems.",
        image: "/devai/images/products/limit_switch_industrial.png",
        datasheet: "#"
    },
    {
        id: "machine-safety-switch",
        productName: "Machine Safety Switch",
        manufacturerName: "Pilz",
        category: "Safety",
        shortDescription: "Safety switch for machine guarding.",
        fullDescription: "Non-contact safety switches for monitoring guard doors and ensuring safe machine operation.",
        image: "/devai/images/products/machine_safety_switch.png",
        datasheet: "#"
    },
    {
        id: "mcb-electrical-switch",
        productName: "MCB Electrical Switch",
        manufacturerName: "Schneider",
        category: "Switchgear",
        shortDescription: "Miniature circuit breaker switch.",
        fullDescription: "Compact MCBs for branch circuit protection in electrical distribution systems.",
        image: "/devai/images/products/mcb_electrical_switch.png",
        datasheet: "#"
    },
    {
        id: "mccb-electrical-switchgear",
        productName: "MCCB Electrical Switchgear",
        manufacturerName: "L&T",
        category: "Switchgear",
        shortDescription: "Molded case circuit breaker for switchgear.",
        fullDescription: "High-capacity MCCBs for main and feeder circuit protection in switchgear assemblies.",
        image: "/devai/images/products/mccb_electrical_switchgear.png",
        datasheet: "#"
    },
    {
        id: "pneumatic-tools",
        productName: "Pneumatic Tools",
        manufacturerName: "Atlas Copco",
        category: "Tools",
        shortDescription: "Air-powered industrial tools.",
        fullDescription: "Pneumatic drills, wrenches, and grinders for heavy-duty industrial applications.",
        image: "/devai/images/products/pneumatic_tools_industrial.png",
        datasheet: "#"
    },
    {
        id: "power-relay",
        productName: "Power Relay",
        manufacturerName: "TE Connectivity",
        category: "Controlgear",
        shortDescription: "High-power switching relay.",
        fullDescription: "Electromechanical power relays for controlling high-current loads in industrial systems.",
        image: "/devai/images/products/power_relay_electrical.png",
        datasheet: "#"
    },
    {
        id: "rtd-sensor",
        productName: "RTD Temperature Sensor",
        manufacturerName: "Omega",
        category: "Sensors",
        shortDescription: "Resistance Temperature Detector.",
        fullDescription: "Accurate RTD sensors for measuring temperature in industrial processes, with high stability and linearity.",
        image: "/devai/images/products/rtd_temperature_sensor.png",
        datasheet: "#"
    },
    {
        id: "safety-relay",
        productName: "Safety Relay",
        manufacturerName: "Pilz",
        category: "Safety",
        shortDescription: "Relay for safety circuits.",
        fullDescription: "Safety relays for monitoring emergency stop circuits and ensuring fail-safe operation.",
        image: "/devai/images/products/safety_relay.png",
        datasheet: "#"
    },
    {
        id: "sfu-switch-fuse-unit",
        productName: "SFU Switch Fuse Unit",
        manufacturerName: "Siemens",
        category: "Switchgear",
        shortDescription: "Switch fuse unit for motor circuits.",
        fullDescription: "Combination switch and fuse units for protection and isolation of motor circuits.",
        image: "/devai/images/products/sfu_switch_fuse_unit.png",
        datasheet: "#"
    },
    {
        id: "v-belt",
        productName: "V Belt",
        manufacturerName: "Gates",
        category: "Mechanical",
        shortDescription: "Industrial V-belt for power transmission.",
        fullDescription: "High-strength V-belts for efficient power transmission in industrial machinery.",
        image: "/devai/images/products/v_belt_industrial.png",
        datasheet: "#"
    },
    {
        id: "vmc-machine-light",
        productName: "VMC Machine Light",
        manufacturerName: "Custom",
        category: "Lighting",
        shortDescription: "LED light for Vertical Machining Centers.",
        fullDescription: "Specialized LED lighting for VMC machines, providing bright illumination for machining operations.",
        image: "/devai/images/products/vmc_machine_light.png",
        datasheet: "#"
    },
    {
        id: "distributed-io",
        productName: "Distributed I/O",
        manufacturerName: "Siemens / Rockwell",
        category: "Automation & Control Components",
        subCategory: "Programmable Logic Controllers",
        shortDescription: "Modular I/O for distributed control systems.",
        fullDescription: "Distributed I/O modules for extending PLC capabilities in remote locations. Supports various communication protocols and provides reliable signal processing.",
        image: "/devai/images/products/distributed-io.png",
        datasheet: "#"
    },
    {
        id: "soft-starter",
        productName: "Soft Starter",
        manufacturerName: "Schneider / ABB",
        category: "Automation & Control Components",
        subCategory: "Variable Frequency Drive Systems",
        shortDescription: "Smooth motor starting and stopping.",
        fullDescription: "Soft starters provide controlled acceleration and deceleration of electric motors, reducing mechanical stress and electrical disturbances.",
        image: "/devai/images/products/soft-starter.png",
        datasheet: "#"
    },
    {
        id: "pressure-switch",
        productName: "Pressure Switch",
        manufacturerName: "Danfoss / Honeywell",
        category: "Automation & Control Components",
        subCategory: "Pressure Switches & Transducers",
        shortDescription: "Pressure monitoring and control.",
        fullDescription: "Pressure switches and transducers for monitoring fluid pressure in industrial systems. Available in various pressure ranges and electrical outputs.",
        image: "/devai/images/products/pressure-switch.png",
        datasheet: "#"
    },
    {
        id: "presence-detector",
        productName: "Presence Detector",
        manufacturerName: "Pepperl+Fuchs",
        category: "Automation & Control Components",
        subCategory: "Presence Detectors",
        shortDescription: "Detection of objects in automation.",
        fullDescription: "Presence detectors for reliable object detection in industrial automation applications. IP67 rated for harsh environments.",
        image: "/devai/images/products/presence-detector.png",
        datasheet: "#"
    },
    {
        id: "coded-magnetic-switch",
        productName: "Coded Magnetic Switch",
        manufacturerName: "Schmersal",
        category: "Automation & Control Components",
        subCategory: "Coded Magnetic Switches",
        shortDescription: "Safety magnetic switch with coding.",
        fullDescription: "Coded magnetic safety switches for machine guarding. Provides high safety levels with unique coding to prevent tampering.",
        image: "/devai/images/products/coded-magnetic-switch.png",
        datasheet: "#"
    },
    {
        id: "switch-fuse-unit",
        productName: "Switch Fuse Unit",
        manufacturerName: "Siemens / L&T",
        category: "Electrical Switching & Protection",
        subCategory: "Switch Fuse Units and Isolators",
        shortDescription: "Combined switching and protection device.",
        fullDescription: "Switch fuse units provide manual switching and fuse protection for electrical circuits. Used for motor control and distribution applications.",
        image: "/devai/images/products/sfu_switch_fuse_unit.png",
        datasheet: "#"
    },
    {
        id: "auto-changeover-system",
        productName: "Auto Source Changeover System",
        manufacturerName: "Schneider / ABB",
        category: "Electrical Switching & Protection",
        subCategory: "Auto Source Changeover Systems",
        shortDescription: "Automatic switching between power sources.",
        fullDescription: "Automatic transfer switches for seamless switching between main and backup power sources. Ensures uninterrupted power supply.",
        image: "/devai/images/products/auto-changeover-system.png",
        datasheet: "#"
    },
    {
        id: "surge-arrester",
        productName: "Surge Arrester",
        manufacturerName: "Siemens / ABB",
        category: "Electrical Switching & Protection",
        subCategory: "Surge Arresters",
        shortDescription: "Protection against voltage surges.",
        fullDescription: "Surge arresters protect electrical equipment from overvoltage transients caused by lightning or switching operations.",
        image: "/devai/images/products/surge-arrester.png",
        datasheet: "#"
    },
    {
        id: "time-switch",
        productName: "Time Switch",
        manufacturerName: "Theben / L&T",
        category: "Electrical Switching & Protection",
        subCategory: "Time Switches / Light Sensitive Switches",
        shortDescription: "Programmable timer for electrical circuits.",
        fullDescription: "Digital time switches for automated control of lighting, heating, and other electrical loads based on time schedules.",
        image: "/devai/images/products/time-switch.png",
        datasheet: "#"
    },
    {
        id: "electronic-overcurrent-relay",
        productName: "Electronic Over Current Relay",
        manufacturerName: "Siemens / ABB",
        category: "Electrical Switching & Protection",
        subCategory: "Electronic Over Current Relays",
        shortDescription: "Advanced overcurrent protection.",
        fullDescription: "Electronic overcurrent relays provide precise protection against overload and short circuit conditions in electrical systems.",
        image: "/devai/images/products/electronic-overcurrent-relay.png",
        datasheet: "#"
    },
    {
        id: "power-meter",
        productName: "Power Meter",
        manufacturerName: "Schneider / Siemens",
        category: "Power Supply & Energy Management",
        subCategory: "Power Meters and Analyzers",
        shortDescription: "Electrical power measurement and monitoring.",
        fullDescription: "Digital power meters for measuring electrical parameters like voltage, current, power, and energy consumption.",
        image: "/devai/images/products/power-meter.png",
        datasheet: "#"
    },
    {
        id: "power-quality-analyzer",
        productName: "Power Quality Analyzer",
        manufacturerName: "Fluke / Hioki",
        category: "Power Supply & Energy Management",
        subCategory: "Power Quality Analyzer",
        shortDescription: "Analysis of electrical power quality.",
        fullDescription: "Portable power quality analyzers for monitoring harmonics, transients, and other power quality parameters.",
        image: "/devai/images/products/power-quality-analyzer.png",
        datasheet: "#"
    },
    {
        id: "pf-capacitor",
        productName: "PF Improvement Capacitor",
        manufacturerName: "EPCOS / ABB",
        category: "Power Supply & Energy Management",
        subCategory: "PF Improvement Capacitor",
        shortDescription: "Power factor correction capacitor.",
        fullDescription: "Power factor improvement capacitors for enhancing electrical system efficiency and reducing energy costs.",
        image: "/devai/images/products/pf-capacitor.png",
        datasheet: "#"
    },
    {
        id: "tower-light",
        productName: "Tower Light",
        manufacturerName: "Patlite / Schneider",
        category: "Industrial Indicators & Signaling",
        subCategory: "Tower Light",
        shortDescription: "Multi-color signal tower.",
        fullDescription: "LED signal towers for visual indication of machine status, alarms, and process conditions in industrial environments.",
        image: "/devai/images/products/tower-light.png",
        datasheet: "#"
    },
    {
        id: "warning-light",
        productName: "Warning / Revolving Light",
        manufacturerName: "Federal Signal",
        category: "Industrial Indicators & Signaling",
        subCategory: "Warning / Revolving Light",
        shortDescription: "Rotating warning beacon.",
        fullDescription: "Revolving warning lights for alerting personnel to hazardous conditions or equipment status.",
        image: "/devai/images/products/warning-light.png",
        datasheet: "#"
    },
    {
        id: "siren-buzzer",
        productName: "Siren / Buzzer",
        manufacturerName: "Patlite / Honeywell",
        category: "Industrial Indicators & Signaling",
        subCategory: "Siren / Buzzer",
        shortDescription: "Audible alarm device.",
        fullDescription: "Industrial sirens and buzzers for audible signaling in noisy industrial environments.",
        image: "/devai/images/products/siren-buzzer.png",
        datasheet: "#"
    },
    {
        id: "push-button",
        productName: "Push Button",
        manufacturerName: "Schneider / Siemens",
        category: "Machine Interface & Operator Control",
        subCategory: "Push Buttons, Switches, Pilot Lights",
        shortDescription: "Manual control interface.",
        fullDescription: "Industrial push buttons and switches for operator control of machinery and processes.",
        image: "/devai/images/products/push-button.png",
        datasheet: "#"
    },
    {
        id: "control-station",
        productName: "Control Station",
        manufacturerName: "Rittal / Schneider",
        category: "Machine Interface & Operator Control",
        subCategory: "Control Stations",
        shortDescription: "Operator control panel.",
        fullDescription: "Pre-assembled control stations with push buttons, selectors, and indicators for machine control.",
        image: "/devai/images/products/control-station.png",
        datasheet: "#"
    },
    {
        id: "pendant-station",
        productName: "Pendant Station",
        manufacturerName: "Schneider / Siemens",
        category: "Machine Interface & Operator Control",
        subCategory: "Pendant Stations",
        shortDescription: "Portable control pendant.",
        fullDescription: "Pendant control stations for crane and hoist operation, providing ergonomic control interfaces.",
        image: "/devai/images/products/pendant-station.png",
        datasheet: "#"
    },
    {
        id: "joystick-controller",
        productName: "Joystick Controller",
        manufacturerName: "Schneider / ABB",
        category: "Machine Interface & Operator Control",
        subCategory: "Joystick Controllers",
        shortDescription: "Multi-axis control device.",
        fullDescription: "Industrial joysticks for precise control of machinery movement in multiple axes.",
        image: "/devai/images/products/joystick-controller.png",
        datasheet: "#"
    },
    {
        id: "industrial-plug-socket",
        productName: "Industrial Plug and Socket",
        manufacturerName: "Mennekes / Schneider",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Industrial Plug and Socket",
        shortDescription: "Heavy-duty electrical connector.",
        fullDescription: "Industrial plugs and sockets for safe and reliable power connections in harsh environments.",
        image: "/devai/images/products/industrial_electrical_switch_socket.png",
        datasheet: "#"
    },
    {
        id: "plug-socket-enclosure",
        productName: "Plug & Socket with Enclosure",
        manufacturerName: "ABB / Siemens",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Plug & Socket with Enclosure",
        shortDescription: "Weatherproof plug and socket assembly.",
        fullDescription: "Enclosed plug and socket combinations for outdoor and industrial applications.",
        image: "/devai/images/products/plug-socket-enclosure.png",
        datasheet: "#"
    },
    {
        id: "cable-drum",
        productName: "Cable Drums",
        manufacturerName: "Custom",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Cable Drums",
        shortDescription: "Cable storage and dispensing.",
        fullDescription: "Cable drums for safe storage and controlled dispensing of electrical cables.",
        image: "/devai/images/products/cable-drum.png",
        datasheet: "#"
    },
    {
        id: "pvc-channel",
        productName: "PVC Channel & MCB Channel",
        manufacturerName: "Legrand / Schneider",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "PVC Channel & MCB Channel",
        shortDescription: "Cable management channel.",
        fullDescription: "PVC channels and MCB channels for organizing and protecting electrical wiring.",
        image: "/devai/images/products/din_rail_electrical.png",
        datasheet: "#"
    },
    {
        id: "heavy-duty-connector",
        productName: "Heavy Duty Connectors",
        manufacturerName: "Harting / Phoenix",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Heavy Duty Connectors",
        shortDescription: "Rugged electrical connector.",
        fullDescription: "Heavy-duty connectors for reliable power and signal connections in industrial environments.",
        image: "/devai/images/products/industrial_power_connector.png",
        datasheet: "#"
    },
    {
        id: "empty-enclosure",
        productName: "Empty Enclosures",
        manufacturerName: "Rittal / Schneider",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Empty Enclosures",
        shortDescription: "Electrical enclosure housing.",
        fullDescription: "Empty electrical enclosures for housing control equipment and protecting against environmental factors.",
        image: "/devai/images/products/empty-enclosure.png",
        datasheet: "#"
    },
    {
        id: "junction-box-ip65",
        productName: "Junction Box IP65",
        manufacturerName: "Hensel / Schneider",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Junction Box IP65",
        shortDescription: "Weatherproof junction box.",
        fullDescription: "IP65 rated junction boxes for protecting electrical connections in outdoor and wet environments.",
        image: "/devai/images/products/abs_electrical_enclosure.png",
        datasheet: "#"
    },
    {
        id: "cooling-fan",
        productName: "Cooling Fan",
        manufacturerName: "ebm-papst / Schneider",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Cooling Fan",
        shortDescription: "Enclosure ventilation fan.",
        fullDescription: "Cooling fans for maintaining optimal temperatures inside electrical enclosures.",
        image: "/devai/images/products/cooling-fan.png",
        datasheet: "#"
    },
    {
        id: "fan-filter",
        productName: "Fan Filter",
        manufacturerName: "Rittal / Schneider",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Fan Filter",
        shortDescription: "Filtered ventilation unit.",
        fullDescription: "Fan filter units for filtered air circulation in electrical enclosures.",
        image: "/devai/images/products/fan-filter.png",
        datasheet: "#"
    },
    {
        id: "heat-shrink",
        productName: "Heat Shrink",
        manufacturerName: "3M / Raychem",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Heat Shrink",
        shortDescription: "Cable insulation tubing.",
        fullDescription: "Heat shrink tubing for electrical insulation and mechanical protection of cables and connections.",
        image: "/devai/images/products/heat-shrink.png",
        datasheet: "#"
    },
    {
        id: "spiral-wrapping",
        productName: "Spiral",
        manufacturerName: "HellermannTyton",
        category: "Enclosures, Wiring & Panel Accessories",
        subCategory: "Spiral",
        shortDescription: "Cable bundling spiral wrap.",
        fullDescription: "Spiral wrapping for organizing and protecting cable bundles.",
        image: "/devai/images/products/spiral-wrapping.png",
        datasheet: "#"
    },
    {
        id: "safety-limit-switch",
        productName: "Safety Limit Switch",
        manufacturerName: "Schmersal / Pilz",
        category: "Safety, Testing & Measurement",
        subCategory: "Safety Products",
        shortDescription: "Safety position switch.",
        fullDescription: "Safety limit switches for monitoring guard positions and ensuring safe machine operation.",
        image: "/devai/images/products/limit_switch_industrial.png",
        datasheet: "#"
    },
    {
        id: "foot-switch",
        productName: "Foot Switch",
        manufacturerName: "Schneider / Siemens",
        category: "Safety, Testing & Measurement",
        subCategory: "Safety Products",
        shortDescription: "Hands-free control switch.",
        fullDescription: "Foot-operated switches for hands-free control of machinery and processes.",
        image: "/devai/images/products/foot-switch.png",
        datasheet: "#"
    },
    {
        id: "pull-cord-switch",
        productName: "Pull Cord Switch",
        manufacturerName: "Schmersal",
        category: "Safety, Testing & Measurement",
        subCategory: "Safety Products",
        shortDescription: "Emergency stop pull cord.",
        fullDescription: "Pull cord switches for emergency stopping of conveyor systems and machinery.",
        image: "/devai/images/products/pull-cord-switch.png",
        datasheet: "#"
    },
    {
        id: "guard-protection-switch",
        productName: "Guard Protection Switch",
        manufacturerName: "Pilz / Schmersal",
        category: "Safety, Testing & Measurement",
        subCategory: "Safety Products",
        shortDescription: "Safety guard monitoring switch.",
        fullDescription: "Safety switches for monitoring the position of protective guards on machinery.",
        image: "/devai/images/products/guard-protection-switch.png",
        datasheet: "#"
    },
    {
        id: "analog-insulation-tester",
        productName: "Analog Insulation Hi Tester",
        manufacturerName: "Hioki / Megger",
        category: "Safety, Testing & Measurement",
        subCategory: "Test & Measurement System",
        shortDescription: "Insulation resistance measurement.",
        fullDescription: "Analog insulation testers for measuring insulation resistance in electrical systems.",
        image: "/devai/images/products/analog-insulation-tester.png",
        datasheet: "#"
    },
    {
        id: "digital-insulation-tester",
        productName: "Digital Insulation Tester",
        manufacturerName: "Fluke / Hioki",
        category: "Safety, Testing & Measurement",
        subCategory: "Test & Measurement System",
        shortDescription: "Digital insulation resistance tester.",
        fullDescription: "Digital insulation testers with advanced features for electrical safety testing.",
        image: "/devai/images/products/digital-insulation-tester.png",
        datasheet: "#"
    },
    {
        id: "high-voltage-insulation-tester",
        productName: "High Voltage Insulation Tester",
        manufacturerName: "Megger / Hioki",
        category: "Safety, Testing & Measurement",
        subCategory: "Test & Measurement System",
        shortDescription: "High voltage insulation testing.",
        fullDescription: "High voltage insulation testers for testing insulation integrity in high-voltage systems.",
        image: "/devai/images/products/high-voltage-insulation-tester.png",
        datasheet: "#"
    },
    {
        id: "automatic-insulation-tester",
        productName: "Automatic Insulation with Stand Tester",
        manufacturerName: "Hioki",
        category: "Safety, Testing & Measurement",
        subCategory: "Test & Measurement System",
        shortDescription: "Automated insulation testing system.",
        fullDescription: "Automatic insulation testers with test stands for high-volume testing applications.",
        image: "/devai/images/products/automatic-insulation-tester.png",
        datasheet: "#"
    },
    {
        id: "electronic-measuring-meter",
        productName: "Electronic Measuring Meters",
        manufacturerName: "Fluke / Hioki",
        category: "Safety, Testing & Measurement",
        subCategory: "Measuring Instruments",
        shortDescription: "Electronic measurement instruments.",
        fullDescription: "Electronic measuring meters for various electrical parameters and industrial measurements.",
        image: "/devai/images/products/electronic-measuring-meter.png",
        datasheet: "#"
    },
    {
        id: "led-voltmeter",
        productName: "LED Indicating Voltmeter / Ammeter",
        manufacturerName: "Schneider / Siemens",
        category: "Safety, Testing & Measurement",
        subCategory: "Measuring Instruments",
        shortDescription: "LED display measuring instrument.",
        fullDescription: "LED indicating voltmeters and ammeters for panel mounting and electrical parameter display.",
        image: "/devai/images/products/led-voltmeter.png",
        datasheet: "#"
    },
    {
        id: "multifunction-meter",
        productName: "Multifunction Meter",
        manufacturerName: "Schneider / Siemens",
        category: "Safety, Testing & Measurement",
        subCategory: "Measuring Instruments",
        shortDescription: "Multi-parameter electrical meter.",
        fullDescription: "Multifunction meters for measuring multiple electrical parameters simultaneously.",
        image: "/devai/images/products/multifunction-meter.png",
        datasheet: "#"
    },
    {
        id: "hour-meter",
        productName: "Hour Meter",
        manufacturerName: "Hengstler / Schneider",
        category: "Safety, Testing & Measurement",
        subCategory: "Measuring Instruments",
        shortDescription: "Equipment runtime counter.",
        fullDescription: "Hour meters for tracking equipment operating time and maintenance scheduling.",
        image: "/devai/images/products/hour-meter.png",
        datasheet: "#"
    }
];

// Export for Node.js environment if needed, otherwise it's a global variable in browser
if (typeof module !== 'undefined' && module.exports) {
    module.exports = productsData;
}
